basics
js-tasks-ru/vue-20230120_evgenyzharikov pull request #2
Opened 2023-01-25 13:08 UTC by eZharikov

2023-01-25 13:08 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-25 23:07 UTC, ShGKme requested changes
В целом всё отлично, но требуются небольшие изменения:
- `01-basics/02-VueCalculator` - убрать лишнюю привязку `:checked`
- `01-basics/03-MarkedList` - использовать привязку классов с объектом
- `01-basics/04-MeetupTitle` - вернуть функцию из методов

2023-01-25 23:07 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +          <label><input v-model="sign" :checked="sign === 'divide'" type="radio" name="operator" value="divide" /> ➗</label>
`v-model="sign"` уже устанавливает свойство `checked`, дублировать его не нужно.

2023-01-25 23:07 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
> +      </button>
Обычно к данным обращаются по короткому пути, без `$data`: `{{ counter }}`

2023-01-25 23:07 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          </li>
Во Vue, когда требуется добавить класс по условию, удобно использовать синтаксис привязки класса объектом. Объект явно описывает, какой класс по какому условию требуется добавлять.

[https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects](https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects) 

Так явно видно, от чего зависит наличие каждого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы. 

И не требуется делать `else` с пустой строкой в тернарном операторе.

2023-01-25 23:07 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +    },
Для использования функции в компоненте её не требуется переносить в методы. В методах компонента должны быть те функции, которые являются частью компонента. Изменяют или используют его свойства, обрабатывают события внутри компонента. Могут в методах также быть и простые функции, если они используются только в других методах этого же компонента и не нужны вне компонента.

Здесь же `fetchMeetupById` - самостоятельная функция.

Самостоятельную функцию могут использовать другие компоненты, функции и прочие модули приложения вне разрабатываемого компонента.

2023-01-25 23:07 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
> +        </label>
Аналогично второй задаче - привязка `:checked` лишняя. `v-model` привязывает `checked` и обрабатывает `@change`.

2023-01-31 16:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-31 17:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-31 17:19 UTC, eZharikov commented on 01-basics/04-MeetupTitle/script.js
> +    },
Да. обычно какие-то функции по обращению к api, если они в нескольких компонентах, записываю в store.
Но в данном примере, не понял, как еще раз обработать функцию еще одним then, чтобы получить финальные данные.
что-то типо ?
const result = fetchMeetupById(meetupId)then((item) => {
            (this.meetup = item);
          });

2023-02-01 00:03 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +    },
> что-то типо ?
Да, только метод нужно вызывать через точку:
```js
fetchMeetupById(meetupId).then()
```

И где-то взять `meetupId`. Переменная `const result` не нужна, если нигде не используется.

Помимо `then()` можно работать с асинхронными функциями в JS через async/await:

```js
this.meetup = await fetchMeetupById(meetupId)
```

2023-02-01 00:06 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +    },
> обычно какие-то функции по обращению к api, если они в нескольких компонентах, записываю в store.

А вот это не очень правильно. Стор - это модуль управления глобальным состоянием приложения. Он может использовать функции работы с api, но он не должен быть местом описания таких функций. Отправка HTTP запросов на API - не ответственность реактивного центрального хранилища.

Функции можно описывать в обычных модулях. Так функцию можно будет использовать в любом месте, где она понадобится: компоненты, модули стора или другие места приложения.

2023-02-01 00:07 UTC, ShGKme requested changes
Изменения приняты, но нужно разобраться с использованием асинхронных функций в `01-basics/04-MeetupTitle`.

2023-02-01 15:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-01 15:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-01 16:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-01 17:01 UTC, closed without merging